### ISSUE TITLE
Is that available to public?

### ISSUE THREAD

**Issue by AhmedAli2003** [YasminMuntaserN/the-wild-oasis#1]
Because I can't access the project link even after login on Vercel

This is error message:

> Team Access Required

> You are signed in as ahmedali2003.

> You cannot access this 
> unique deployment URL as you are not a member of the team. You can view the latest version of this branch by >requesting access to the up-to-date deployment URL

> Log in with a different Vercel Account

**Comment by YasminMuntaserN** [comment]
try it now I think the problem is solved

**Comment by AhmedAli2003** [comment]
It is, thanks
